github/urls.py
from django.contrib import admin

from django.urls import *
from django.conf.urls import *
from register.views import *
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('register.urls')),
    url(r'^$',index.as_view(),name='home')


]

register/urls.py
from django.conf.urls import url
from .views import *
from . import views
app_name='register'

urlpatterns = [
    url(r'^$',views.index.as_view(),name='index'),
    url(r'^register',UserFormView.as_view(),name='register'),
    url(r'^login$',Login,name='login'),
    url(r'^temp$',temp,name='temp')
]

register/views.py
from django.shortcuts import render,redirect
from django.views import generic
from django.contrib.auth.models import User
from django import forms
from django.views.generic import View
from django.contrib.auth import authenticate,login

# Create your views here.
class index(generic.TemplateView):
    template_name= 'register/loggedin.html'

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','password']

class UserFormView(View):
    form_class=UserForm
    template_name='register/user_form.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form =self.form_class(request.POST)

        if form.is_valid():
            user=form.save(commit=False)

            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user.set_password(password)
            user.save()

            if user is not None:

                return render(request,'register/login.html',{'register':True})


        return  render(request,self.template_name,{'form':form})
def temp(request):
    return  render(request,'register/login.html')
def Login(request):
        if request.method == "POST":
            uname = request.POST.get('uname',default=None)
            pas = request.POST.get('pass')
            user=authenticate(username=uname,password=pas)

            if user is not None:
                if user.is_active:
                    login(request,user)

                return redirect('register:index')

        return render(request,'register/user_form.html' )

register/templates/register/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" >
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" ></script>
    <title>GitHub</title>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="{% url 'register:index' %}">GitHub</a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'register:register' %}"><span class="glyphicon glyphicon-login"></span>SignUp</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="temp">Login</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#"></a>
    </li>
  </ul>
  <form class="form-inline" action="">
    <input class="form-control" type="text" placeholder="Search Github">&nbsp;&nbsp;&nbsp;
    <button class="btn btn-success" type="submit">Search</button>
  </form>

</nav>

{% block body %}
{% endblock %}

</body>
</html>

register/templates/register/form-temp.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.error }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

register/templates/register/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" >
    <link rel="stylesheet" href="style.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" ></script>
    <title>GitHub</title>
</head>
<body>
    <!--
    you can substitue the span of reauth email for a input with the email and
    include the remember me checkbox
    -->
    {% if register %}
        <p class="label label-success">Account created successfully</p>
    {% endif %}
    <div class="container">
        <div class="card card-container">
            <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
            <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
            <p id="profile-name" class="profile-name-card"></p>
            <form class="form-signin" method="post" action="{% url 'register:login' %}">
                {% csrf_token %}
                <span id="reauth-email" class="reauth-email"></span>
                <input type="text" id="inputEmail" class="form-control" placeholder="Username" name="uname" required autofocus>
                <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="pass" required>
                <div id="remember" class="checkbox">
                    <label>
                        <input type="checkbox" value="remember-me"> Remember me
                    </label>
                </div>
                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>
            </form><!-- /form -->
            <a href="{% url 'register:register' %}" class="forgot-password">
                Create Account
            </a>
            <a href="#" class="forgot-password">
                Forgot the password?
            </a>
        </div><!-- /card-container -->
    </div><!-- /container -->
</body>
</html>

register/templates/register/user_form.html
{% extends 'register/base.html' %}



{% block body %}
    <div class="container-fluid ">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body jumbotron" >

                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'register/form-temp.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}